# Generated by Django 3.2.19 on 2023-05-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20230428_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enter',
            name='updated_on',
        ),
    ]
